### ISSUE TITLE
Address fields not displaying

### ISSUE THREAD

**Issue by team44** [strickdj/acf-field-address#15]
I am using this in a plugin - thanks for the resource.

I upgraded AFC to 5.3.xx and then this plugin. Now my address field doesn't display.

Anyone report anything on your side or do you see issues with the fields displaying after and upgrade?

<img width="1656" alt="screen shot 2016-03-24 at 5 59 28 pm" src="https://cloud.githubusercontent.com/assets/2211225/14032574/356716a2-f1ea-11e5-9eac-4d812edf6a12.png">

**Comment by strickdj** [comment]
Can you test this branch: https://github.com/strickdj/acf-field-address/tree/hotfix/5.1.1

**Comment by team44** [comment]
Thanks for the effort, but no go. I reverted to this hotfix with my current ACF ( 5.3.6 ) and then I went down to 5.3.4 - still the same issue. Tried it as a stand alone plugin just to be sure it wasn't the way I was including - no go / same issue.

Adding a new address field works, showing one that was converted from ACF 4 to 5, no go.

Thanks again for the code. I'll look deeper later and see if I can track down.

**Comment by strickdj** [comment]
From the screenshot it looks like there is a javascript error.

**Comment by team44** [comment]
Those are actually CSS errors. But I'll be digger into this deeper soon. I'll let you know what I find.

**Comment by team44** [comment]
Daris,

This was partly my goof I believe.

So the upgrade itself doesn't keep currently html layout settings, you have to redo them. (meaning after we upgrade, we have to go into the ACF settings for the field and reorganize the layout of the fields).

It works now of course.

**Comment by strickdj** [comment]
Hmm, Thanks for the update. I will look into it.
