### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by htmled** [strickdj/acf-field-address#17]
I'm running WordPress 4.4.4 with ACF Pro 5.3.2.2 and am getting the following error in my WordPress Admin on the Add Post page that has an ACF field using the Address field type. (I didn't change any of the default settings for the address, city, etc.)

`Warning: Invalid argument supplied for foreach() in /var/www/site/wp-content/plugins/acf-address/src/app/plugins/acf-address/acf-address-v5.php on line 259`

**Comment by strickdj** [comment]
What version of this plugin are you using?

**Comment by somethumb** [comment]
I've got that too. I've just downloaded the latest version here.

**Comment by LukeAbell** [comment]
Me too

**Comment by mcaskill** [comment]
The solution:

```
public function load_value($value, $post_id, $field) {
  $new_value = [];
  if (is_array($value)) {
    foreach($value as $k => $v) {
      switch($k) {
        case 'address1':
          $new_value['street1'] = $v;
          break;
        case 'address2':
          $new_value['street2'] = $v;
          break;
        case 'address3':
          $new_value['street3'] = $v;
          break;
        case 'postal_code':
          $new_value['zip'] = $v;
          break;
        default:
          $new_value[$k] = $v;
      }
    }
  }

  return $new_value;
}
```

**Comment by cherrypj** [comment]
Thanks, @mcaskill !
