### ISSUE TITLE
question relating to how the tests work

### ISSUE THREAD

**Issue by damienh** [strickdj/acf-field-address#20]
Hi, This isnt a bug, but I do have a question about how you have got your tests working. I am testing acf in an app using codeception and iv come across an error when trying to select elements like the select tag.

 I see here https://github.com/strickdj/acf-field-address/blob/master/tests/acceptance/CreateNewFieldCept.php#L9 that you simply state `$I->selectOption('form select.field-type', 'address');` to get the select tag. Iv found iv ran into issues with that as the input fields have dynamic id's added to both the `id` and `name` elements. 

I wonder how you got round this? I tried using the implementation you have but it fails to find them.

**Comment by strickdj** [comment]
I never got those acceptance tests to work reliably, but I dont remember having the specific issue you mention.

Also, Its been quite awhile since ive visited this code.

Sorry I cant be of much help.

**Comment by damienh** [comment]
Not to worry thought best to check. Thanks for replying.
